// src/components/OpenAPI/operation/OperationExamples/OperationExamplesList.tsx
import type { ClientId, TargetId } from "@scalar/snippetz";
import { createEffect } from "solid-js";

interface Props<T extends TargetId> {
  target: TargetId;
  client: ClientId<T>;
  children: string;
}

export function OperationExamplesList({ target, client, children }: Props<TargetId>) {
  let containerRef: HTMLDivElement | undefined;

  createEffect(() => {
    if (!containerRef) return;

    const currentActiveExample = containerRef.querySelector(`operation-example[active="true"]`);
    const targetExample = containerRef.querySelector(
      `operation-example[target="${target}"][client="${client}"]`,
    );

    currentActiveExample?.setAttribute("active", "false");
    targetExample?.setAttribute("active", "true");
  });

  return <div ref={containerRef} innerHTML={children} />;
}

// src/components/OpenAPI/operation/OperationExamples/OperationExamplesList.svelte
<script lang="ts">
  import type { ClientId, TargetId } from "@scalar/snippetz";
  import type { Snippet } from "svelte";

  interface Props<T extends TargetId> {
    target: TargetId
    client: ClientId<T>
    children: Snippet
  }


  let { target, client, children }: Props<TargetId> = $props();
  let list: HTMLDivElement | null = null;

  $effect(() => {
    if (!list) return;

    const currentActiveExample = list.querySelector(`operation-example[active="true"]`);
    const targetExample = list.querySelector(
      `operation-example[target="${target}"][client="${client}"]`,
    );

    currentActiveExample?.setAttribute("active", "false");
    targetExample?.setAttribute("active", "true");
  })
</script>

<div bind:this={list}>{@render children()}</div>
